# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/batbox_2013.jpg", description: "Installation de l'abri chauffé pour Petits Rhinolophes dans la grotte en 2013", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/carte_Revogne_1770-1778_Ferraris.png", description: "Carte de Ferraris de 1777", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/carte_Revogne_1820.jpg", description: "Plan cadastral de Revogne en 1820", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/champs_Damilot_1904.jpg", description: "Vue du château du 17e (carte postale de 1904)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/champs_Damilot_2012.jpg", description: "Vue du château du 17e (photo de 2012)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/Chantier_de_fouilles_arche%CC%81ologiques_2013.jpg", description: "Chantier de fouilles archéologiques en 2013", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/chapelle_1945_2.jpg", description: "Vue de la chapelle (photo de 1945)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/chapelle_1945.jpg", description: "Vue de la chapelle (photo de 1945) ", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/chapelle_2009_1.jpg", description: "Vue de la chapelle (photo de 2009)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/chapelle_2010_1.jpg", description: "Vue de la chapelle (photo de 2010)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/chapelle_2010_2.jpg", description: "Vue de la chapelle (photo de 2010)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/chapelle_2011_1.jpg", description: "Vue de la chapelle (photo de 2011)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/chapelle_interieur_2_1945.jpeg", description: "Vue intérieure de la chapelle Saint-Etienne (photo de 1945)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/chapelle_interieur_2_1972.jpeg", description: "Vue intérieure de la chapelle Saint-Etienne (photo de 1972)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/chapelle_interieur_1972.jpeg", description: "Vue intérieure de la chapelle Saint-Etienne (photo de 1972)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/chapelle_interieur_2012.jpg", description: "Vue intérieure de la chapelle Saint-Etienne (photo de 2012)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/Charles_le_Temeraire.jpg", description: "Portrait de Charles le Téméraire, Duc de Bourgogne (1433-1477)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/chateau_2.jpg", description: "Vue du château du 17e et de la poivrière (photo de 2009)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/chateau_3_2009.jpeg", description: "Vue du château du 17e (photo de 2009)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/chateau_cour_2010.jpg", description: "Vue de la cour intérieure du château-ferme du 17e (photo de 2010)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/chateau_ferme_1947.jpg", description: "Vue de la cour intérieure du château-ferme du 17e (photo de 1947)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/crash_Mirage_1984.jpg", description: "Crash du Mirage (photo de 1984)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/crash_Mirage_2006.jpg", description: "Croix du souvenir en mémoire du Capitaine Demortier (photo de 2006)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/dreve_tilleuls_2008.jpg", description: "Drève des tilleuls - Voie d'accès vers l'ancien château fort (photo de 2008)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/fours_a_chaux_1895.jpg", description: "Fours à chaux encore visible à droite de l'image (carte postale de 1895)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/Jean-Franc%CC%A7ois_de_Pierpont.jpg", description: "Portrait de Jean-François de Pierpont (1683-1767)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/Marie_Jose%CC%80phe_de_Noust.jpg", description: "Portrait de Marie-Josèphe de Noust (1761-1842)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/moulin_2013_1.jpg", description: "Moulin à eau - Production de farine (photo de 2013)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/moulin_2013_2.jpg", description: "Moulin à eau (photo de 2013)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/moulin_2013_3.jpg", description: "Moulin à eau (photo de 2013)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/moulin_interieur_2003.jpg", description: "Moulin à eau - meules à blé (photo de 2003)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/Philippe_le_Bon.jpg", description: "Philippe le Bon, Duc de Bourgogne (1396-1467)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/phylactere_2.jpg", description: "Phylactère de Revogne datant du XIIe siècle et conservé au Musée d'Histoire de Namur", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/phylactere.jpg", description: "Phylactère de Revogne datant du XIIe siècle et conservé au Musée d'Histoire de Namur", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/pont_sur_la_Wimbe_2006.jpg", description: "Pont métallique sur la Wimbe (photo de 2006)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/porte_de_Lomprez_1892.jpeg", description: "Porte de Lomprez (carte postale de 1892)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/porte_de_Lomprez_1900.jpg", description: "Porte de Lomprez (carte postale de 1900)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/porte_de_Lomprez_2008.jpg", description: "Porte de Lomprez (photo de 2008)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/presbytere_1947.jpg", description: "Presbytère de Revogne en 1947", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/presbytere_2009.jpg", description: "Presbytère de Revogne en 2009", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/Revogne_fouilles_dec_2013.pdf", description: "Chantier de fouilles archéologiques en 2013", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/sceau_de_la_ville_libre_1241.jpg", description: "Sceau de la ville libre de Revogne datant de 1241 et montrant les 3 tours de l'enceinte", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/site_archeologique_2013_1.jpg", description: "Visite du chantier de fouilles archéologiques en 2013", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/site_archeologique_2013_2.jpg", description: "Ancien seuil de cheminée avec tessons en terre cuite", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/St+Roch.JPG", description: "Saint-Roch - Statue en bois polychrome du 16e (photo de 2012)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/statue_Saint_Urbain_1969.jpg", description: "Saint-Urbain - Statue du 16e en bois polychrome (photo de 1969)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/statue_Saint_Urbain_2012.jpg", description: "Saint-Urbain - Statue en bois polychrome (photo de 2012)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/village_1904_1.jpg", description: "Le hameau de Revogne (carte postale de 1904)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/village_2008.jpg", description: "Le hameau de Revogne (photo de 2008)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/voie_romaine_1.jpg", description: "Ancienne voie romaine (dessin de coupe)", media_type: "photo")
Medium.create(url: "https://s3.eu-central-1.amazonaws.com/walloniatimemachine/pictures+revogne/voie_romaine_2010.jpg", description: "Ancienne voie romaine (photo de 2010)", media_type: "photo")
